const GET_ALL_USER = "GET_ALL_USER";
const FILTER_BY_EMAIL = "FILTER_BY_EMAIL";
const FILTER_BY_MOBILE = "FILTER_BY_MOBILE";
const ERROR = "ERROR";
const LOADING = "LOADING";
export {
  GET_ALL_USER,
  FILTER_BY_EMAIL,
  FILTER_BY_MOBILE,
  ERROR,
  LOADING
}
